set serveroutput on;

/*
drop table my_clob;
create table my_clob (
 id           number generated by default on null as identity,
 name         varchar2(1000),
 clob_content clob
);

create or replace procedure p_log_clob(p_name varchar2, p_clob clob)
is
  pragma autonomous_transaction;
begin
  delete from my_clob;
  insert into my_clob (name, clob_content) values (p_name, p_clob);
  commit;
end;
/
truncate table my_clob;
*/

-- APEX_T_EXPORT_FILE
/*
create or replace type wwv_flow_t_export_file force is object (
    name     varchar2(255),
    contents clob
)

-- APEX_T_EXPORT_FILES
create or replace type wwv_flow_t_export_files is table of wwv_flow_t_export_file
*/

-----------------------------
-- GET_APPLICATION
-- gets application as CLOB
declare
  v_apex_export_files apex_t_export_files; -- table of apex_t_export_file
begin
  v_apex_export_files := apex_export.get_application(p_application_id => 114
                                                   , p_with_acl_assignments => true 
                                                    );
  dbms_output.put_line(v_apex_export_files(1).name); 
  dbms_output.put_line(length(v_apex_export_files(1).contents)); 
  p_log_clob(v_apex_export_files(1).name, v_apex_export_files(1).contents);
end;
/

select * from my_clob;

-----------------------------
-- GET_APPLICATION with split
-- splits application in CLOBs
declare
  v_apex_export_files apex_t_export_files;
begin
  v_apex_export_files := apex_export.get_application(114, p_split => true);
  for i in v_apex_export_files.first..v_apex_export_files.last
  loop
    dbms_output.put_line(v_apex_export_files(i).name||' - '||length(v_apex_export_files(i).contents));
  end loop;
end;
/
-- get feedback
/*
function get_feedback (
    p_workspace_id      in number,
    p_with_date         in boolean  default false,
    p_since             in date     default null,
    p_deployment_system in varchar2 default null )
    return wwv_flow_t_export_files;
*/
declare
  v_apex_export_files apex_t_export_files;
begin
  v_apex_export_files := apex_export.get_feedback(
    p_workspace_id => apex_util.find_security_group_id ('SIOUG2018'),
    p_since        => date '2018-01-01'
  );  
  
  for i in v_apex_export_files.first..v_apex_export_files.last
  loop
    dbms_output.put_line(v_apex_export_files(i).name||' - '||length(v_apex_export_files(i).contents));
  end loop;
end;
/

-- get_workspace
/*
function get_workspace (
    p_workspace_id          in number,
    p_with_date             in boolean default false,
    p_with_team_development in boolean default false,
    p_with_misc             in boolean default false )
    return wwv_flow_t_export_files;
*/
declare
  v_apex_export_files apex_t_export_files;
begin
  v_apex_export_files := apex_export.get_workspace(
    p_workspace_id => apex_util.find_security_group_id ('SIOUG2018')
  );  
  
  for i in v_apex_export_files.first..v_apex_export_files.last
  loop
    dbms_output.put_line(v_apex_export_files(i).name||' - '||length(v_apex_export_files(i).contents));
  end loop;
end;
/

-- get_workspace_files
/*
function get_workspace_files (
    p_workspace_id in number,
    p_with_date    in boolean default false )
    return wwv_flow_t_export_files;
*/
declare
  v_apex_export_files apex_t_export_files;
begin
  v_apex_export_files := apex_export.get_workspace_files(
    p_workspace_id => apex_util.find_security_group_id ('SIOUG2018')
  );  
  
  for i in v_apex_export_files.first..v_apex_export_files.last
  loop
    dbms_output.put_line(v_apex_export_files(i).name||' - '||length(v_apex_export_files(i).contents));
  end loop;
end;
/
